defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: bookmarknext
  password: bookmarknext
  host: localhost
  port: 5432

development:
  database: bookmarknext_development
  <<: *defaults

test:
  database: bookmarknext_test
  <<: *defaults

production:
  database: bookmarknext_production
  <<: *defaults
